spring.application.name=criptografia
server.port=8081

# Configuración de SQLite
spring.datasource.url=jdbc:sqlite:cripto.db
spring.datasource.driver-class-name=org.sqlite.JDBC

# Configuración de Hibernate/JPA
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Configuración de Gmail
spring.mail.host=smtp.gmail.com
spring.mail.port=465
spring.mail.username=sandoval.espinoza.moises.3im5@gmail.com
spring.mail.password=${SMTP_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
